### ISSUE TITLE
TODO: parse WINBIO_BIR structure at pointer

### ISSUE THREAD

**Issue by leitner** [JcBernack/WinBioNET#3]
Hi, in the function CaptureSample(...) the sample is saved in a IntPtr variable. So my question is, how must that be parsed to get the sample of the fingerprinter?

**Comment by JcBernack** [comment]
I don't know exactly, that's why i skipped it. From what I understand part of the structure will even be specific to the sensor you're using. There is some information on msdn, but I won't be able to work on it. https://msdn.microsoft.com/en-us/library/windows/hardware/ff536459(v=vs.85).aspx
