### ISSUE TITLE
Can I use your WinBioNET convert image data to image?

### ISSUE THREAD

**Issue by tsuiweiwei** [JcBernack/WinBioNET#5]
hi JcBernack
I have a 0xFF3249..... data from customer database, they told me it's fingerprint image data and enrolled from bioApi 1.1 and WBF. 

after long time search...finally I found you, wrapped wbf in C#, I just want to ask how to use your winbionet to converter image data to a image?

**Comment by JcBernack** [comment]
Hi @tsuiweiwei,

I don't know how you would use WBF to get an acutal image. Probably you will have to find out what format the image is stored in and parse it yourself, but I don't really know. The format may even be specific to the sensor used to create it.

This is just a wrapper, it won't help you with finding out what to do in the first place.

**Comment by tsuiweiwei** [comment]
@JcBernack
Thanks for your reply, no more further questions.
